name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x]

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install
      run: |
        go get github.com/aliyun/alibaba-cloud-sdk-go
        go get github.com/goji/httpauth
    
    - name: Check core
      run: go vet ./sdk

    - name: Check service
      run: go vet ./services/...

    - name: Build core
      run: go build ./sdk

    - name: Build service
      run: go build ./services/...

    - name: Function Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./sdk/...

    - name: Integration Test
      run: go test -v -timeout 120s ./integration/...
      env:
        REGION_ID: ${{ secrets.REGION_ID }}
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
        USER_ID: ${{ secrets.USER_ID }}
        RSA_FILE_AES_KEY: ${{ secrets.RSA_FILE_AES_KEY }}
        PUBLIC_KEY_ID: ${{ secrets.PUBLIC_KEY_ID }}
        JOB_INDEX: ${{ strategy.job-index }}
    
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash)